# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(input):
    fibArray = [1, 2];
    sum = 2;
    while fibArray[-1] <= input:
        fibArray.append(fibArray[-1] + fibArray[-2]);
        if fibArray[-1] % 2 == 0:
            sum += fibArray[-1];
    print(sum);

fibonacci(4000000);
